Optimisation: Replacing listView in CarSelectionActivity with Recycler View having well designed Cardviews
enviroCar/enviroCar-app pull request #1012
Opened 2024-12-18 13:12 UTC by Jdbarad

### Description
This activity presently contains listView for showing the list of cars which is not an efficient approach.
This listView needs to be replaced with RecyclerView having well-designed CardViews which will lead to a better user interface as well as better app performance.

### How did it get fixed?
Replace ListView with RecyclerView, Create `CarSelectionRecyclerAdapter` for `mCarRecyclerView` 
Create a function & method that is also required in `CarSelectionListAdapter`. Also added CardView for a better user experience.

### Conclusion 
Now, `CarSelectionActivity` uses RecyclerView, That better for App performance. Also Solved Broken car selection radio button #927

2025-01-03 12:51 UTC, SebaDro requested changes

2025-01-03 12:51 UTC, SebaDro commented on org.envirocar.app/res/layout/activity_car_selection_layout_carlist_entry.xml
> +    app:cardCornerRadius="@dimen/cardview_corner_radius"
I think the definition of this dimension is missing within the [dimens.xml](https://github.com/enviroCar/enviroCar-app/blob/master/org.envirocar.app/res/values/dimens.xml). Thus, building fails. Can you fix it and add the missing dimension?

2025-01-03 17:16 UTC, Jdbarad commented on org.envirocar.app/res/layout/activity_car_selection_layout_carlist_entry.xml
> +    app:cardCornerRadius="@dimen/cardview_corner_radius"
Yes Sure.

2025-01-06 12:09 UTC, SebaDro approved these changes

2025-01-06 12:09 UTC, merged