Tapping on User Statistics to navigate to MY TRACKS .
enviroCar/enviroCar-app pull request #554
Opened 2020-12-31 16:38 UTC by asaikarthikeya

#553 
It is natural tendency to click on the statistics to view complete tracking details rather than viewing it explicitly. 

https://user-images.githubusercontent.com/70392921/103418398-77bcf200-4bb4-11eb-8a59-4e30f0c39a72.mp4

2020-12-31 16:41 UTC, asaikarthikeya commented
@dewall sir please review.

2021-01-01 18:00 UTC, arvindnegi1 requested changes

2021-01-01 18:00 UTC, arvindnegi1 commented on org.envirocar.app/src/org/envirocar/app/injection/BaseInjectorActivity.java
> +
not needed here

2021-01-01 18:00 UTC, arvindnegi1 commented on org.envirocar.app/src/org/envirocar/app/injection/BaseInjectorActivity.java
> +
undo all this changes

2021-01-01 18:00 UTC, arvindnegi1 commented on org.envirocar.app/src/org/envirocar/app/injection/BaseInjectorActivity.java
> +    }
not to be done here.
Please follow the proper structure.
Do this on DashboardFragment 
for eg-: BottomNavigationView bottomView= getActivity.findViewById(R.id.navigation);
then use ButterKnife @Onlick on user statistics view id 
then you can select item

2021-01-01 18:00 UTC, arvindnegi1 commented on org.envirocar.app/src/org/envirocar/app/handler/userstatistics/UserStatisticsProcessor.java
undo

2021-01-01 18:00 UTC, arvindnegi1 commented on org.envirocar.app/src/org/envirocar/app/handler/userstatistics/UserStatisticsProcessor.java
> +    protected static final class UserStatisticsHolder{
same here, undo

2021-01-01 18:08 UTC, arvindnegi1 commented
@asaikarthikeya  Please read my comments  ;)
also remove the unwanted commit that is not associated with this PR.
Please change the base branch to develop.
And always make PRs to develop branch.

2021-01-01 18:12 UTC, asaikarthikeya commented
@arvindnegi1 Sure . I will make the necessary changes and update you. thank you

2021-01-02 15:37 UTC, closed without merging