updated
enviroCar/enviroCar-app pull request #555
Opened 2021-01-02 15:34 UTC by asaikarthikeya

#553

2021-01-02 15:57 UTC, asaikarthikeya commented
@arvindnegi1 please review .

2021-01-04 17:54 UTC, arvindnegi1 commented on org.envirocar.app/src/org/envirocar/app/views/dashboard/DashboardFragment.java
> +    protected void Go_to_MyTracks(){
use camelCase for function name

2021-01-04 17:55 UTC, arvindnegi1 requested changes

2021-01-04 17:55 UTC, arvindnegi1 commented on org.envirocar.app/src/org/envirocar/app/views/dashboard/DashboardFragment.java
> +    protected void Go_to_MyTracks(){
use camelCase for function name

2021-01-07 12:03 UTC, arvindnegi1 commented
@asaikarthikeya please do required changes.
As told you in mail. Follow Java Naming conventions.

2021-01-07 15:23 UTC, asaikarthikeya commented
I changed the name using name conventions but did not squash the commits(My
bad) will do that soon.
Grateful to receive your support. thank you.



On Thu, Jan 7, 2021 at 5:33 PM Arvind Negi <notifications@github.com> wrote:

> @asaikarthikeya <https://github.com/asaikarthikeya> please do required
> changes.
> As told you in mail. Follow Java Naming conventions.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/enviroCar/enviroCar-app/pull/555#issuecomment-756075453>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQZBYWJ7L77EOC5UUO5N5JLSYWPIXANCNFSM4VREHY5Q>
> .
>

2021-01-11 15:04 UTC, closed without merging