Snackbar output changed when car is Reselected.
enviroCar/enviroCar-app pull request #565
Opened 2021-01-16 04:47 UTC by asaikarthikeya

Fixes : #559 

https://user-images.githubusercontent.com/70392921/103769262-ff3db180-5049-11eb-8639-c9ab8ba6d665.mp4

2021-02-17 08:14 UTC, asaikarthikeya commented
@bpross-52n  please review the changes. Thankyou

2021-07-23 17:39 UTC, Akash-Ramjyothi commented
Superseded by #768.

2021-08-10 15:15 UTC, SebaDro requested changes

2021-08-10 15:15 UTC, SebaDro commented on org.envirocar.app/src/org/envirocar/app/views/carselection/CarSelectionActivity.java
> +                        Car car1 = mCarManager.getCar();
`car1` is not a meaningful variable name. Please, revise it.

2021-08-11 15:59 UTC, merged