Make the car selected if only 1 car is present in MyCars.
enviroCar/enviroCar-app pull request #744
Opened 2021-06-09 06:34 UTC by asaikarthikeya

Fixes #550 

https://user-images.githubusercontent.com/70392921/121304958-a3d65f00-c91a-11eb-9b63-82872e1f2123.mp4

2021-06-09 13:20 UTC, asaikarthikeya commented
@bpross-52n Please review the changes sir. Thank you.

2021-06-11 11:12 UTC, SebaDro requested changes

2021-06-11 11:12 UTC, SebaDro commented on org.envirocar.app/src/org/envirocar/app/views/carselection/CarSelectionActivity.java
> +        startActivity(getIntent());
Restarting the activity to refresh the view is not a good practice. I would rather suggest you to find a way to set the corresponding RadioButton as selected for the selected car.

2021-06-15 18:51 UTC, arvindnegi1 commented
@asaikarthikeya Can you please first merge the updated develop or gsoc2021 branch in your current branch otherwise i can see it undo some changes which is the part of new car selection process.

2021-08-04 13:25 UTC, closed without merging