Showing ProgressDialog at the time of bluetooth pairing
enviroCar/enviroCar-app pull request #977
Opened 2023-03-06 06:02 UTC by SanjaySargam

Fixes #969 

**ScreenRecording**
https://user-images.githubusercontent.com/65113071/223030922-e5b9c2e7-f463-4730-86db-abf3ecc7c056.mp4

2023-03-06 16:43 UTC, SebaDro commented
Hi @SanjaySargam . Thanks for your contribution. 

I really like the solution for showing a progress bar when pairing performs. Just a small suggestion: we already have a [DialogUtils ](https://github.com/enviroCar/enviroCar-app/blob/master/org.envirocar.app/src/org/envirocar/app/views/utils/DialogUtils.java) helper class that provides some methods to create a `MaterialAlertDialogBuilder` with progress bar. It would be great, if you could use this helper class to create the dialog, since it also applies the enviroCar theme on the dialog, which preserves consistence in the UX

What do you think about it?

2023-03-06 16:44 UTC, SebaDro requested changes
Hi @SanjaySargam . Thanks for your contribution. 

I really like the solution for showing a progress bar when pairing performs. Just a small suggestion: we already have a [DialogUtils ](https://github.com/enviroCar/enviroCar-app/blob/master/org.envirocar.app/src/org/envirocar/app/views/utils/DialogUtils.java) helper class that provides some methods to create a `MaterialAlertDialogBuilder` with progress bar. It would be great, if you could use this helper class to create the dialog, since it also applies the enviroCar theme on the dialog, which preserves consistence in the UX

What do you think about it?

2023-03-06 16:46 UTC, SanjaySargam commented
> Hi @SanjaySargam . Thanks for your contribution.
> 
> I really like the solution for showing a progress bar when pairing performs. Just a small suggestion: we already have a [DialogUtils ](https://github.com/enviroCar/enviroCar-app/blob/master/org.envirocar.app/src/org/envirocar/app/views/utils/DialogUtils.java) helper class that provides some methods to create a `MaterialAlertDialogBuilder` with progress bar. It would be great, if you could use this helper class to create the dialog, since it also applies the enviroCar theme on the dialog, which preserves consistence in the UX
> 
> What do you think about it?

Ok I will use existing Dialog in helper class

2023-07-31 07:03 UTC, SebaDro requested changes
Please, change the color of the Bluetooth icon to be white and select the develop branch as target branch for your pull request. After that I will merge it.

2023-07-31 07:03 UTC, SebaDro commented on org.envirocar.app/res/drawable/baseline_bluetooth_connected_24.xml
I'd rather expect the Bluetooth icon to be white, as every ProgressDialog has a white icon.

2023-07-31 12:05 UTC, SanjaySargam commented
> Please, change the color of the Bluetooth icon to be white and select the develop branch as target branch for your pull request. After that I will merge it.

@SebaDro Ok 
To achieve this, I need to delete this PR and make another one right?

2023-07-31 12:10 UTC, SebaDro commented
Well, I think it's possible to edit the present pull request and change the target branch. If not, just create a new one and close the old.

2023-08-01 08:35 UTC, SebaDro approved these changes

2023-08-01 09:37 UTC, merged