Changed makeIsDashboardFragmentFalse() to onDashboardFragmentFalse()
enviroCar/enviroCar-app pull request #980
Opened 2023-03-07 14:52 UTC by devAyushDubey

Fixes #979 

The purpose of `makeIsDashboardFragmentFalse()` was to set [isDashboardFragment](https://github.com/devAyushDubey/enviroCar-app/blob/edf19e15c480f84bac6f6183c95fc564aa32b9b9/voicecommand/src/main/java/org/envirocar/voicecommand/handler/MetadataHandler.kt#L33) to `false`, which is fulfilled by the method [onDashboardFragmentFalse()](https://github.com/devAyushDubey/enviroCar-app/blob/edf19e15c480f84bac6f6183c95fc564aa32b9b9/voicecommand/src/main/java/org/envirocar/voicecommand/handler/MetadataHandler.kt#L32) now.

![Screenshot (1015)](https://user-images.githubusercontent.com/33064931/223457943-46b8d706-ce0a-4ff1-9683-4b709be4b9cb.png)

2023-03-07 16:51 UTC, SanjaySargam commented
![Screenshot 2023-03-07 222018s](https://user-images.githubusercontent.com/65113071/223491755-32078888-2076-4bca-8101-c6aaee1e01ac.png)
I am getting error here too. How can I resolve it

2023-07-11 19:00 UTC, cdhiraj40 requested changes

2023-07-13 19:32 UTC, closed without merging

2023-07-13 19:32 UTC, devAyushDubey commented
Fixed in #992

2023-07-14 15:32 UTC, devAyushDubey commented on voicecommand/src/main/java/org/envirocar/voicecommand/BaseAimybox.kt
> +        fun setCurrentAimybox(aimybox: Aimybox) {
Yeah, we can, I thought it's a good practice to use getters/setters, and the code looks structured, for maybe in the future if we decide to make it private. Although, I have no issues doing it directly, let me know.