Added Vosk Adaptation Guide in Readme
enviroCar/enviroCar-app pull request #992
Opened 2023-07-12 08:31 UTC by devAyushDubey

This PR contains Vosk Model Adaptation Guide, currently added in Readme.md

2023-07-13 12:24 UTC, cdhiraj40 commented
Hey @devAyushDubey, let's move this to another file inside the project, probably `vosk-model-adaption`
Other than that, everything looks good!

2023-07-13 12:24 UTC, cdhiraj40 requested changes
Hey @devAyushDubey, let's move this to another file inside the project, probably vosk-model-adaption
Other than that, everything looks good!

2023-07-14 09:26 UTC, SebaDro commented
> Hey @devAyushDubey, let's move this to another file inside the project, probably vosk-model-adaption Other than that, everything looks good!

I also think that this guide should be part of a separate README. Maybe, create one, which is intended for voice command stuff inside the voice command module.

2023-07-14 09:44 UTC, SebaDro requested changes

2023-07-14 09:44 UTC, SebaDro commented on README.md
> +There are many issues which can lead to bad accuracy from model mismatches to software bugs. See [accuracy](https://alphacephei.com/vosk/accuracy) guide for more detailed information on how to debug
Be careful with copy&pasting whole sections from another documentation. You'd rather consider a reqrite or add appropriate credits.

2023-07-14 09:50 UTC, SebaDro commented on README.md
> +There are many issues which can lead to bad accuracy from model mismatches to software bugs. See [accuracy](https://alphacephei.com/vosk/accuracy) guide for more detailed information on how to debug
I've noticed several other sections that have been copy and pasted. Please, revise your whole documentation. If sections does not provide any new instructions than the original one from the [Vosk homepage](https://alphacephei.com/vosk/adaptation), please remove these sections and just link to the original guide.

2023-07-25 09:31 UTC, SebaDro approved these changes
Looks good to me. I will merge it, as soon as @cdhiraj40 also approves.

2023-07-26 12:26 UTC, cdhiraj40 approved these changes
Looks good to me! Ready to merge :)

2023-07-31 06:42 UTC, merged